WebXodeTechnologies/webxode

webxode/app/page.tsx, webxode/components/Hero.tsx, webxode/components/ui/FloatingNav.tsx, webxode/components/ui/MagicButton.tsx, webxode/components/ui/Spotlight.tsx, webxode/dummy.text, webxode/tailwind.config.ts
=> Hero Section Completed

webxode/components/Services.tsx
=> Services Component update

webxode/app/page.tsx, webxode/app/provider.tsx, webxode/components/GlobalConnection.tsx, webxode/components/RecentWorks.tsx, webxode/components/Services.tsx, webxode/data/index.ts
Format - pretty - all files formatted - success
=> Format - pretty

webxode/components/RecentWorks.tsx
Recent works testimonials updated with cachy text
=> Recent work test array Update

webxode/app/globals.css, webxode/app/page.tsx, webxode/components/RecentProjects.tsx, webxode/components/Services.tsx, webxode/components/ui/PinContainer.tsx, webxode/components/ui/SparklesPreview.tsx, webxode/components/ui/sparkles.tsx, webxode/data/index.ts, webxode/package-lock.json, webxode/package.json
Project Comp update
new projects component added
=> Project Comp update

webxode/components/RecentProjects.tsx
Recent projects issues resolved
=> Recent projects issues resolved

webxode/app/page.tsx, webxode/components/BookDemo.tsx, webxode/components/Faq.tsx, webxode/components/Footer.tsx, webxode/components/Macbookscroll.tsx, webxode/components/TechStack.tsx, webxode/components/Testimonial.tsx
All dummy pages added
need to complete the landing page asap
=> All dummy pages added

webxode/next.config.ts
Next.js Config update, 
build run success, as of now no issues
=> Next.js Config update

webxode/components/TechStack.tsx, webxode/components/Testimonial.tsx, webxode/components/ui/InfiniteMovingCards.tsx, webxode/data/index.ts
=> Testimonials Comp Complete

webxode/components/Testimonial.tsx, webxode/data/index.ts
Testimonial comp update and test complete
=> Testimonial comp update

webxode/components/Faq.tsx, webxode/data/index.ts
Custom Faq Component Update Q & A
need to work on footer and other links and pages
=> Custom Faq Component Update Q & A

webxode/components/BookDemo.tsx, webxode/components/ui/vortex.tsx, webxode/package-lock.json, webxode/package.json
=> Book Demo Component

webxode/app/globals.css, webxode/app/page.tsx, webxode/components/Macbookscroll.tsx, webxode/components/ui/HeroHighlight.tsx, webxode/components/ui/MacbookScroll.tsx, webxode/package-lock.json, webxode/package.json, webxode/postcss.config.mjs, webxode/tailwind.config.ts
Macbook scroll Component Update, 
bg hightlight component added,
need to work on Footer and links
=> Macbook scroll Component Update

webxode/app/page.tsx, webxode/components/Footer.tsx
=> Footer Component

webxode/app/globals.css, webxode/components/ui/FloatingNav.tsx, webxode/components/ui/MagicButton.tsx, webxode/data/index.ts
nav items and nav bar fix with updated links
=> nav item and nav bar fix

webxode/app/globals.css, webxode/app/page.tsx, webxode/components/BookDemo.tsx, webxode/components/OurApproach.tsx, webxode/components/RecentProjects.tsx, webxode/components/Services.tsx, webxode/components/ui/MacbookScroll.tsx, webxode/tailwind.config.ts
=> corrections

webxode/components/Faq.tsx, webxode/components/Services.tsx, webxode/components/TechStack.tsx, webxode/components/Testimonial.tsx
=> corrections2

webxode/components/Footer.tsx
=> Footer update

webxode/app/layout.tsx, webxode/app/page.tsx
=> Layout Change

webxode/app/who-are-we/page.tsx, webxode/data/index.ts
Array Update-  company process - matching with Key for SEO optimistaion
=> Array Update

webxode/app/who-are-we/page.tsx
=> Demo Cta added

webxode/components/AboutUs.tsx
=> About us Comp button Update

webxode/components/ServicesPage/DigitalServices.tsx
Digital Services - component resused
=> Digital Services

webxode/components/ServicesPage/DigitalBanner.tsx
Digital Banner - image needs to change - subject to copyright issues
=> Digital Banner

webxode/app/what-we-do/page.tsx, webxode/components/ServicesPage/DevelopementProcess.tsx
Correction in services - dev process
=> Correction in services - dev process

webxode/components/ServicesPage/ProposalCTA.tsx, webxode/components/ui/FlipWords.tsx, webxode/components/ui/shooting-stars.tsx, webxode/components/ui/stars-background.tsx
=> services - Proposal CTA

webxode/components/BookDemo.tsx, webxode/components/OurApproach.tsx, webxode/data/index.ts
=> Correction in Demo Comp

webxode/components/BookDemo.tsx, webxode/components/Macbookscroll.tsx, webxode/components/ui/MacbookScroll.tsx
=> Reponsive issues - Homepage

webxode/components/WorkFlow/DevelopmentProcess.tsx, webxode/components/WorkFlow/HeroSection.tsx
services page - development process, 
video needs to get included
=> services page - development process

webxode/components/DemoPage/DemoCTA.tsx
=> Format Changes - pretty

webxode/app/terms-and-conditions/page.tsx
=> terms and conditions

webxode/components/WorkFlow/Payment.tsx
Changes in the payment Process
=> Changes in the payment Process

webxode/app/demo/page.tsx, webxode/components/DemoPage/ContactAerosol.js, webxode/components/DemoPage/ContactText.js, webxode/components/DemoPage/styles.css, webxode/package-lock.json, webxode/package.json, webxode/tailwind.config.ts
=> New Testing Component Added

webxode/components/DemoPage/Herobanner.tsx
Animation using Framer- but need to work
=> Animation using Framer- but need to work

webxode/components/Footer.tsx
=> Footer Github- update

webxode/components/Footer.tsx
=> responsive Fix

webxode/components/Footer.tsx
Footer completed - format changes
=> Footer completed - format changes

webxode/app/page.tsx, webxode/components/ScrollVideo.tsx, webxode/components/ui/ContainerScroll.tsx
=> Video - Homepage

webxode/components/Whataspp.tsx
WhatsApp Business Account Added
=> WhatsApp Business Account Added

webxode/components/Footer.tsx, webxode/components/Services.tsx
=> Fixing Broken Links

webxode/components/ui/MacbookScroll.tsx
=> Build Error Fix

webxode/components/AboutPage/CompanyTimeline.tsx, webxode/components/AboutPage/Team.tsx, webxode/components/DemoPage/ContactForm.jsx, webxode/components/Macbookscroll.tsx, webxode/components/RecentWorks.tsx, webxode/components/ScrollVideo.tsx, webxode/components/Services.tsx, webxode/components/ServicesPage/DigitalServices.tsx, webxode/components/Testimonial.tsx, webxode/components/WorkFlow/DevelopmentProcess.tsx, webxode/components/ui/FlipWords.tsx, webxode/components/ui/HeroHighlight.tsx, webxode/components/ui/MacbookScroll.tsx, webxode/components/ui/Timeline.tsx, webxode/components/ui/animated-testimonials.tsx, webxode/components/ui/backgroundLines.tsx
=> Changes in the dark mode

webxode/components/TechStack.tsx
=> Error Fix _ Image Change

webxode/public/google194d5b15285006b3.html, webxode/public/googleaa1023c38c9331cd.html
=> Sitemap file added

webxode/app/layout.tsx, webxode/app/page.tsx, webxode/components/AboutPage/Team.tsx, webxode/components/AboutUs.tsx, webxode/public/google194d5b15285006b3.html
=> Changes In the website

webxode/app/blog/[slug]/page.tsx, webxode/data/index.ts, webxode/package-lock.json, webxode/package.json, webxode/tailwind.config.ts
=> All Blog and slug items Added

webxode/app/careers/page.tsx, webxode/app/terms-and-conditions/page.tsx, webxode/components/TermsandCondtions/page.tsx
Carrers Page and Terms and conditions page updated
=> Carrers Page and Terms and conditions page updated
